services:
  database:
    image: mysql:8.3
    container_name: ms-scoreusers-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: directus_db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - directus-net

  directus:
    image: directus/directus:11.5.1
    container_name: directus-app
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    depends_on:
      - database
    environment:
      KEY: 'random-key'
      SECRET: "replace-with-random-value"
      DB_CLIENT: "mysql"
      DB_HOST: database
      DB_PORT: "3306"
      DB_DATABASE: directus_db
      DB_USER: root
      DB_PASSWORD: root
      ADMIN_EMAIL: "jordannandjo11@gmail.com"
      ADMIN_PASSWORD: "d1r3ctu5"
      WEBSOCKETS_ENABLED: "true"
    networks:
      - directus-net

#  phpmyadmin:
#    image: phpmyadmin:5.2.1-apache
#    container_name: ms-scoreuser-pma
#    environment:
#      PMA_HOST: database
#    ports:
#      - "8082:80"
#    networks:
#      - directus-net


volumes:
  db_data:

networks:
  directus-net:
